### PR TITLE
Binarize fonts during generation

### PR DESCRIPTION
**Pull request by Caerind**
Hello !

I don't know if this will help anyone, but I find that feature quite useful for me.

It is easy to enable/disable by simply changing the "binarizeC" variable in main.

### CODE REVIEW

**Comment by juliettef** [comment]
Thanks for this PR. There are a few small changes I would prefer prior to accepting the PR, and one larger one.
- The main change would be to download the TTF to a variable and not to disk to avoid the need for temporary files and file deletions. In my test the code ended up deleting IconsFontaudio.h in error when the ttf was not downloaded. See get_intermediate_representation() for example.
- Set default binarizeC = False
- Rename binarizeC to ttf2headerC (and other uses of binarize) to clarify the intention is to turn the binary ttf file to C compilable variable in header.
- Undo change to font_file_name_ttf: I've [inverted the files order in font_ttf instead](https://github.com/juliettef/IconFontCppHeaders/blob/174eafd05bd0e876e75ae94377507579733d61fa/GenerateIconFontCppHeaders.py#L176).

**Comment by juliettef** [comment]
Hi @Caerind,

Thanks again for the PR. I decided to make the changes myself so I could simplify the code by modifying the overall data structure. There was also an issue with codepoints referring to several ttfs.

Changes to the ttf headers:
- Split ttf header files to one per ttf as some icon fonts refer to several ttfs. See for example see FA5 pro. Renamed output ttf header files to include both the icon font header file name and the ttf file name. 
- added comments and '#pragma once' to the prelude
- added '_ttf' suffix to the array name

The ttf header files compile but I haven't used them. The code is in branch [ttf2headerC](https://github.com/juliettef/IconFontCppHeaders/tree/ttf2headerC). Your feedback would be appreciated, but if I don't hear back from you I'll merge this into master on Sunday 13th Dec.

**Comment by Caerind** [comment]
Hi @juliettef,
Sorry for the late answer, I'm not in a programming mood apart from work right now...

I read your commits on the ttf2headerC branch and everything seems fine to me (much better that my version with temporary files obviously). I'm not on my computer right now so I didn't test it, I will test it on tuesday, but again, it seems fine.

Thanks for the changes!

**Comment by juliettef** [comment]
No worries whatsoever. I'll wait for your test results, no rush.

**Comment by Caerind** [comment]
Not totally fan of the naming for the output files, but otherwise it works fine :)

**Comment by juliettef** [comment]
Thanks for your feedback. Regarding the output files names, it'as an easy way to avoid duplicate file names (e.g. FA5 and FA5 pro's fa-regular-400.ttf, fa-solid-900.ttf etc) and to keep the files alphabetically grouped with their respective codepoints. Do you have an alternative you'd like to suggest?

**Comment by Caerind** [comment]
It's good enough like that. I will change the filenames on my side for now.
Thanks a lot for this :)

**Comment by juliettef** [comment]
Squash merged to master. Thanks again

**Pull request merged**
