### PR TITLE
Added support for Font Awesome regular, solid, and brands fonts

### PR DESCRIPTION
**Pull request by codecat**
This adds support for Font Awesome's new way of doing fonts:

* Separate regular, solid, and brands fonts
* New `icons.yml` format

### CODE REVIEW

**Comment by codecat** [comment]
Not sure about the `FAS`, `FAB`, `FAR` abbrevations, they could probably be more clear. Thoughts?

**Comment by juliettef** [comment]
Many thanks, looking into this now.

**Comment by codecat** [comment]
Actually running into some problems with merging solid & brands fonts right now. Within ImGui, I'm pretty sure I will need a ttf file that has both solid and brands icons in them, otherwise it won't merge well..

**Comment by juliettef** [comment]
Yes this is complex as we're also trying to preserve backward compatibility. (The FA 4.0 version moved to this branch https://github.com/FortAwesome/Font-Awesome/tree/fa-4/fonts)
I need to have a think about how best to do this.

**Comment by codecat** [comment]
Also see referenced issue above, which is a hack that allows ImGui to merge overlapping font ranges.

**Comment by ocornut** [comment]
Will look into it from Dear ImGui side.
Suggestions: for this PR may I suggest the files so be named, e.g `IconsFontAwesome5_Regular.h`
And I believe it would be fine to rename the old header to `IconsFontAwesome4.h`.

**Comment by juliettef** [comment]
Merged changes into master. Thanks for your help @codecat.

I've combined FA solid and regular since they have identical codepoints (regular is a subset of solid). Note FA have mixed the codepoint values for solid and brand hence these two can't be easily be used simultaneously at the moment as you noted.

Whilst it's not perfect it's the best we could come up with for now. Let me know if you have any problem with this approach.

**Comment by codecat** [comment]
Thanks for the update!

**Pull request merged**
