### PR TITLE
Add Rust language support to `GenerateIconFontCppHeaders.py`

### LINKED ISSUE #17: Support for Rust?
Would it be in the scope of this repo to include the font definitions also for Rust, to be used with e.g. https://github.com/Gekkio/imgui-rs ?

### PR DESCRIPTION
**Pull request by Bradshaw**
This pull request adds the `LanguageRust` class to `GenerateIconFontCppHeaders.py`.
Here is an example of a `.rs` file generated with these changes applied: https://gist.github.com/Bradshaw/f7fb7ddd1a8f60c7cebfe960be0b3d48

Because I do not have access to the Font Awesome 5 Pro sources, I'm not submitting the generated files alongside this pull request. That way all of the generated files can be added in the same commit.

Note that I kept the file naming scheme in the same style as the other generated files, but this would flag as a warning in the cargo toolchain when used in a Rust project.
Also, since Rust has a solid dependency and package manager ([Cargo](https://doc.rust-lang.org/cargo/) it might be worthwhile making the Rust version available as a crate on [crates.io](https://crates.io/). I'd be happy to help this happen, as well as set up a CI/CD pipeline to automate updates to such a package.

### CODE REVIEW

**Comment by juliettef** [comment]
Thanks! This looks fine to me but I'd like to get some feedback from other Rust users.

In C and C++ you can use the codepoints very easily in strings, for ex. 
```ImGui::Text( "Use this icon: " ICON_FA_PAINT_BRUSH " for Paint" );```

Is the current Rust generator creating code that is as easy as it can be to use in Rust? (since it looks like rust doesn't have automatic string literals concatenation).

**Comment by laundmo** [comment]
in Rust you would need to do
```rs
format!("Use this icon: {} for Paint", ICON_FA_PAINT_BRUSH);
```
which isn't quite that nice

**Comment by dougbinks** [comment]
Can this also be used with the `concat!` macro (note I'm not a Rust programmer)?

```Rust
concat!( "Use this icon: ", ICON_FA_PAINT_BRUSH, " for Paint" )
```

**Comment by Toasterson** [comment]
Note this code will not take care of loading the font for the user. That is OS depedendant and would need a crate that does that. This crate may be only a addition for other crates that allow custom fonts in the console. But for that it will work great.

**Comment by Bradshaw** [comment]
> Can this also be used with the `concat!` macro (note I'm not a Rust programmer)?
> 
> ```rust
> concat!( "Use this icon: ", ICON_FA_PAINT_BRUSH, " for Paint" )
> ```

No, `concat` is only for concatenating literals: https://doc.rust-lang.org/core/macro.concat.html



> Note this code will not take care of loading the font for the user. That is OS depedendant and would need a crate that does that. This crate may be only a addition for other crates that allow custom fonts in the console. But for that it will work great.

Indeed. I believe that's the case for the other supported languages. If I understand correctly, this project simply provides named constants for the Unicode values that map to icons in a collection of popular icon fonts.

**Comment by juliettef** [comment]
Thanks @Bradshaw and everyone who commented. I've merged the PR without modification (see [@Bradshaw's original comment for details](https://github.com/juliettef/IconFontCppHeaders/pull/31#issue-1652197208)).

In order to keep this repository as simple as possible and due to not knowing Rust I haven't included any package management, but if anyone implements this I'll link to it.

**Comment by laundmo** [comment]
Re: package management, do you mean link to it as in, someone else should publish the package? I'd imagine the proper way to go would be to add a CI to publish automatically when updated.

**Pull request merged**
